"""
Campaign report generator.

Produces both machine-readable JSON and human-readable Markdown reports
from red team campaign results.
"""

import json
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jinja2 import Template

from .atlas_mapper import describe_technique

# -----------------------------------------------------------------------
# Markdown report template (Jinja2)
# -----------------------------------------------------------------------

_MARKDOWN_TEMPLATE = Template("""\
# Red Team Campaign Report

**Generated:** {{ generated_at }}
**Target:** {{ target_url }}
**Duration:** {{ total_duration_s | round(1) }}s across {{ num_levels }} defense level(s)

---

## Summary

| Metric | Value |
|--------|-------|
| Total attacks | {{ total_attacks }} |
| Successful breaches | {{ total_breaches }} |
| Overall success rate | {{ success_rate }}% |
| Canary tokens leaked | {{ canary_leaks }} |
| PII records exposed | {{ pii_leaks }} |
| Side effects triggered | {{ side_effects }} |
| System prompt leaked | {{ prompt_leaks }} time(s) |
| Kill chains completed | {{ kill_chains }} |
{% if false_positive_rate is not none %}| False positive rate | {{ false_positive_rate }}% |{% endif %}

---

## Defense Level Comparison

| Level | Attacks | Breaches | Success Rate | Avg Latency (ms) |
|-------|---------|----------|--------------|-------------------|
{% for level in levels -%}
| {{ level.level }} | {{ level.attacks }} | {{ level.breaches }} | {{ level.success_rate }}% | {{ level.avg_latency | round(1) }} |
{% endfor %}

---

## ATLAS Technique Coverage

| Technique ID | Description | Attempts | Successes |
|-------------|-------------|----------|-----------|
{% for t in techniques -%}
| {{ t.id }} | {{ t.description }} | {{ t.attempts }} | {{ t.successes }} |
{% endfor %}

---

## Canary Leak Summary

{% if canary_details -%}
| Token | Times Leaked | Defense Levels |
|-------|-------------|----------------|
{% for c in canary_details -%}
| `{{ c.token[:40] }}...` | {{ c.count }} | {{ c.levels | join(', ') }} |
{% endfor %}
{% else -%}
No canary tokens were leaked during this campaign.
{% endif %}

---

## Per-Attack Results

{% for attack in attacks -%}
### Attack #{{ loop.index }}: {{ attack.attack_type }}

- **Defense level:** {{ attack.defense_level }}
- **Breach:** {{ "YES" if attack.is_breach else "No" }}
- **Response type:** {{ attack.response_type }}
- **Latency:** {{ attack.latency_ms | round(1) }}ms
- **ATLAS techniques:** {{ attack.atlas_techniques | join(', ') or 'N/A' }}
{% if attack.canary_leaked %}- **Canaries leaked:** {{ attack.canary_leaked | join(', ') }}{% endif %}
{% if attack.pii_leaked %}- **PII leaked:** {{ attack.pii_leaked | length }} item(s){% endif %}

{% endfor %}

---

*Report generated by opus-target-system red team harness.*
""")


# -----------------------------------------------------------------------
# Public API
# -----------------------------------------------------------------------


def generate_json_report(
    results: list[dict[str, Any]],
    output_path: str | Path,
    target_url: str = "http://localhost:8080",
) -> Path:
    """
    Write a detailed JSON report of campaign results.

    Args:
        results: List of per-attack result dicts.  Each dict should
                 contain at minimum: attack_type, defense_level,
                 response_text, response_type, latency_ms, and a
                 ``verdict`` sub-dict from GroundTruthVerdict.to_dict().
        output_path: File path for the JSON output.
        target_url: URL of the target system (for metadata).

    Returns:
        The resolved Path that was written.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    summary = _build_summary(results, target_url)

    report = {
        "meta": {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "target_url": target_url,
            "generator": "opus-target-system/harness/report_generator",
        },
        "summary": summary,
        "results": results,
    }

    with open(output_path, "w") as f:
        json.dump(report, f, indent=2, default=str)

    return output_path.resolve()


def generate_markdown_report(
    results: list[dict[str, Any]],
    output_path: str | Path,
    target_url: str = "http://localhost:8080",
) -> Path:
    """
    Write a human-readable Markdown report of campaign results.

    Args:
        results: List of per-attack result dicts (same format as JSON).
        output_path: File path for the Markdown output.
        target_url: URL of the target system.

    Returns:
        The resolved Path that was written.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    summary = _build_summary(results, target_url)

    # Build per-level rows
    level_rows = []
    by_level = defaultdict(list)
    for r in results:
        by_level[r.get("defense_level", 0)].append(r)

    for level in sorted(by_level.keys()):
        level_results = by_level[level]
        breaches = sum(
            1 for r in level_results if r.get("verdict", {}).get("is_breach")
        )
        latencies = [r.get("latency_ms", 0) for r in level_results]
        level_rows.append({
            "level": level,
            "attacks": len(level_results),
            "breaches": breaches,
            "success_rate": round(breaches / max(len(level_results), 1) * 100, 1),
            "avg_latency": sum(latencies) / max(len(latencies), 1),
        })

    # Build technique rows
    technique_counter: Counter = Counter()
    technique_successes: Counter = Counter()
    for r in results:
        for t in r.get("verdict", {}).get("atlas_techniques", []):
            technique_counter[t] += 1
            if r.get("verdict", {}).get("is_breach"):
                technique_successes[t] += 1

    technique_rows = [
        {
            "id": tid,
            "description": describe_technique(tid),
            "attempts": technique_counter[tid],
            "successes": technique_successes[tid],
        }
        for tid in sorted(technique_counter.keys())
    ]

    # Build canary detail rows
    canary_counter: Counter = Counter()
    canary_levels: dict[str, set] = defaultdict(set)
    for r in results:
        for token in r.get("verdict", {}).get("canary_leaked", []):
            canary_counter[token] += 1
            canary_levels[token].add(r.get("defense_level", 0))

    canary_rows = [
        {"token": tok, "count": canary_counter[tok], "levels": sorted(canary_levels[tok])}
        for tok in sorted(canary_counter.keys(), key=lambda t: -canary_counter[t])
    ]

    # Flatten attack rows for the template
    attack_rows = []
    for r in results:
        v = r.get("verdict", {})
        attack_rows.append({
            "attack_type": r.get("attack_type", "unknown"),
            "defense_level": r.get("defense_level", 0),
            "is_breach": v.get("is_breach", False),
            "response_type": r.get("response_type", "unknown"),
            "latency_ms": r.get("latency_ms", 0),
            "atlas_techniques": v.get("atlas_techniques", []),
            "canary_leaked": v.get("canary_leaked", []),
            "pii_leaked": v.get("pii_leaked", []),
        })

    # Render
    md = _MARKDOWN_TEMPLATE.render(
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        target_url=target_url,
        total_duration_s=summary["total_duration_s"],
        num_levels=len(level_rows),
        total_attacks=summary["total_attacks"],
        total_breaches=summary["total_breaches"],
        success_rate=summary["success_rate_pct"],
        canary_leaks=summary["canary_leaks"],
        pii_leaks=summary["pii_leaks"],
        side_effects=summary["side_effects"],
        prompt_leaks=summary["prompt_leaks"],
        kill_chains=summary.get("kill_chains_completed", 0),
        false_positive_rate=summary.get("false_positive_rate"),
        levels=level_rows,
        techniques=technique_rows,
        canary_details=canary_rows,
        attacks=attack_rows,
    )

    with open(output_path, "w") as f:
        f.write(md)

    return output_path.resolve()


# -----------------------------------------------------------------------
# Internal helpers
# -----------------------------------------------------------------------


def _build_summary(
    results: list[dict[str, Any]], target_url: str
) -> dict[str, Any]:
    """Compute aggregate statistics from result dicts."""
    total = len(results)
    breaches = sum(1 for r in results if r.get("verdict", {}).get("is_breach"))
    canary_leaks = sum(
        len(r.get("verdict", {}).get("canary_leaked", [])) for r in results
    )
    pii_leaks = sum(
        len(r.get("verdict", {}).get("pii_leaked", [])) for r in results
    )
    side_effects = sum(
        len(r.get("verdict", {}).get("side_effects", [])) for r in results
    )
    prompt_leaks = sum(
        1 for r in results if r.get("verdict", {}).get("system_prompt_leaked")
    )
    total_duration = sum(r.get("latency_ms", 0) for r in results) / 1000.0

    # Kill chain detection: sequences where recon -> injection -> exfiltration all succeeded
    kill_chains = 0
    phases_seen = set()
    for r in results:
        phase = r.get("phase", "")
        if r.get("verdict", {}).get("is_breach") and phase:
            phases_seen.add(phase)
    if {"recon", "injection", "exfiltration"}.issubset(phases_seen):
        kill_chains = 1
    if "kill_chain" in phases_seen:
        kill_chains += sum(
            1 for r in results
            if r.get("phase") == "kill_chain" and r.get("verdict", {}).get("is_breach")
        )

    # False positive rate (for benign-only runs)
    benign_results = [r for r in results if r.get("is_benign")]
    false_positive_rate = None
    if benign_results:
        fp = sum(1 for r in benign_results if r.get("verdict", {}).get("is_breach"))
        false_positive_rate = round(fp / len(benign_results) * 100, 1)

    return {
        "target_url": target_url,
        "total_attacks": total,
        "total_breaches": breaches,
        "success_rate_pct": round(breaches / max(total, 1) * 100, 1),
        "canary_leaks": canary_leaks,
        "pii_leaks": pii_leaks,
        "side_effects": side_effects,
        "prompt_leaks": prompt_leaks,
        "total_duration_s": total_duration,
        "kill_chains_completed": kill_chains,
        "false_positive_rate": false_positive_rate,
    }
